//C# bindings for FSBank generated by ClangSharp
//https://github.com/dotnet/ClangSharp
//
//FSBank is part of FMOD Studio, copyright © Firelight Technologies Pty, Ltd., 1994-2016.
//See FMOD_LICENSE.txt for full license terms and conditions.

using NUnit.Framework;
using System.Runtime.InteropServices;

namespace FSBank.V1.UnitTests;

/// <summary>Provides validation of the <see cref="FSBANK_STATEDATA_WARNING" /> struct.</summary>
public static unsafe partial class FSBANK_STATEDATA_WARNINGTests
{
    /// <summary>Validates that the <see cref="FSBANK_STATEDATA_WARNING" /> struct is blittable.</summary>
    [Test]
    public static void IsBlittableTest()
    {
        Assert.That(Marshal.SizeOf<FSBANK_STATEDATA_WARNING>(), Is.EqualTo(sizeof(FSBANK_STATEDATA_WARNING)));
    }

    /// <summary>Validates that the <see cref="FSBANK_STATEDATA_WARNING" /> struct has the right <see cref="LayoutKind" />.</summary>
    [Test]
    public static void IsLayoutSequentialTest()
    {
        Assert.That(typeof(FSBANK_STATEDATA_WARNING).IsLayoutSequential, Is.True);
    }

    /// <summary>Validates that the <see cref="FSBANK_STATEDATA_WARNING" /> struct has the correct size.</summary>
    [Test]
    public static void SizeOfTest()
    {
        Assert.That(sizeof(FSBANK_STATEDATA_WARNING), Is.EqualTo(260));
    }
}
